<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0-windows10.0.19041.0</TargetFrameworks>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Kawazu" Version="1.1.4" />
      <PackageReference Include="LibNMeCab.IpaDicBin" Version="0.10.0" />
    </ItemGroup>

</Project>